global using PermissionBasedAuthorization.Controllers.Base;
global using PermissionBasedAuthorization.Core.Constants;
global using PermissionBasedAuthorization.Core.Entities;
global using PermissionBasedAuthorization.Models;